services:
  neo4j_db:
    image: neo4j:2025.02
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/drink_beer_have_fun
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - neo4j_data:/data

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - neo4j_db
    environment:
      - NEO4J_URI=neo4j://neo4j_db
      - NEO4J_AUTH=neo4j/drink_beer_have_fun

volumes:
  neo4j_data:
